server:
  port: "8080"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Seoul
    username: root
    password: supreme327

  jpa:
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

  mvc:
    static-path-pattern: /**

  web:
    resources:
      static-locations:
        - classpath:/META-INF/resource
        - classpath:/resources/
        - classpath:/static/
        - classpath:/public/
      add-mappings: true
